#facebook
FB_EMAIL = "FB_EMAIL"
FB_PASSWORD = "FB_PASS"

GROUP_LINK = "https://www.facebook.com/groups/1374475339518708"
SEARCH_FOR = "למסירה"
#telegram
API_KEY = "TELEGRAM_BOT_API_NAME"
USERNAME = "TELEGRAM_USERNAME"
CHAT_ID = "TELEGRAM_CHAT"